export const ROUTES = {
  Home: "/",
  Register: "/register",
  Login: "/login",
  Profile: "/profile",
  Settings: "/settings",
  GoogleAuthSuccess: "/auth/success",
  Welcome: "/welcome",
  VerifyEmail: "/auth/verify-email",
  ConfirmEmailChange: "/auth/confirm-email-change",
  PasswordRecovery: "/passwordRecovery",
  ResetPassword: "/auth/reset-password",
  AdminPanel: "/adminPanel",
  TwoFactorVerify: "/auth/2fa-verify",
  Workspace: "/workspace/:id",
  Onboarding: "/onboarding",
  Dashboard: "/dashboard",
  Invite: "/invite/:token",
  Portal: "/portal",
} as const;
